server {
    server_name hermes.upshalter.com;
    return 301 https://workstation.upshalter.com/hermes$request_uri;
    
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/hermes.upshalter.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hermes.upshalter.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = hermes.upshalter.com) {
        return 301 https://workstation.upshalter.com/hermes$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name hermes.upshalter.com;
    return 404;
}
