#!/bin/bash
# Generate status page HTML for status.upshalter.com
# Auto-generated by FASE 6 (2026-05-06)

OUTPUT="/var/www/status/index.html"
mkdir -p /var/www/status

# Collect data
SYSTEMD=$(systemctl list-units --type=service --all | grep -i hermes | awk '{print $1, $3, $4, $5}')
DOCKER=$(docker ps -a --filter "name=hermes" --format "{{.Names}}|{{.Status}}|{{.Image}}")
DOMAINS=("workspace.upshalter.com" "hermes.upshalter.com" "chat.upshalter.com")

# Generate HTML
cat > "$OUTPUT" << 'EOF'
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upshalter Status Dashboard</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0f172a; color: #e2e8f0; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { color: #60a5fa; margin-bottom: 10px; font-size: 2rem; }
        .subtitle { color: #94a3b8; margin-bottom: 30px; }
        .section { background: #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 20px; border: 1px solid #334155; }
        h2 { color: #38bdf8; margin-bottom: 15px; font-size: 1.3rem; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #0f172a; color: #94a3b8; text-align: left; padding: 10px; border-bottom: 1px solid #334155; }
        td { padding: 10px; border-bottom: 1px solid #334155; }
        .status-up { color: #4ade80; }
        .status-down { color: #f87171; }
        .status-warning { color: #fbbf24; }
        .domain-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
        .domain-card { background: #0f172a; padding: 15px; border-radius: 6px; border: 1px solid #334155; }
        .domain-card h3 { font-size: 1rem; margin-bottom: 5px; }
        .timestamp { color: #64748b; font-size: 0.9rem; text-align: right; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ Upshalter Status Dashboard</h1>
        <p class="subtitle">Real-time status layanan Hermes Agent di VPS</p>
        
        <!-- Systemd Services -->
        <div class="section">
            <h2>⚙️ Systemd Services</h2>
            <table>
                <tr><th>Service</th><th>Status</th><th>Description</th></tr>
EOF

# Add systemd rows
while read -r line; do
    NAME=$(echo $line | awk '{print $1}')
    LOAD=$(echo $line | awk '{print $2}')
    ACTIVE=$(echo $line | awk '{print $3}')
    SUB=$(echo $line | awk '{print $4}')
    
    if [ "$ACTIVE" = "active" ]; then
        STATUS_CLASS="status-up"
        STATUS_ICON="✅"
    else
        STATUS_CLASS="status-down"
        STATUS_ICON="❌"
    fi
    
    echo "                <tr><td>$NAME</td><td class='$STATUS_CLASS'>$STATUS_ICON $ACTIVE ($SUB)</td><td></td></tr>" >> "$OUTPUT"
done <<< "$SYSTEMD"

cat >> "$OUTPUT" << 'EOF'
            </table>
        </div>
        
        <!-- Docker Containers -->
        <div class="section">
            <h2>🐳 Docker Containers</h2>
            <table>
                <tr><th>Container</th><th>Status</th><th>Image</th></tr>
EOF

# Add docker rows
echo "$DOCKER" | while IFS='|' read -r NAME STATUS IMAGE; do
    if [[ "$STATUS" == *"Up"* ]]; then
        STATUS_CLASS="status-up"
        STATUS_ICON="✅"
    else
        STATUS_CLASS="status-down"
        STATUS_ICON="❌"
    fi
    
    echo "                <tr><td>$NAME</td><td class='$STATUS_CLASS'>$STATUS_ICON $STATUS</td><td>$IMAGE</td></tr>" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'EOF'
            </table>
        </div>
        
        <!-- Domain Health -->
        <div class="section">
            <h2>🌐 Domain Health</h2>
            <div class="domain-grid">
EOF

# Add domain cards
for DOMAIN in "${DOMAINS[@]}"; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN" 2>/dev/null)
    if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "301" ] || [ "$HTTP_CODE" = "302" ]; then
        STATUS_CLASS="status-up"
        STATUS_TEXT="✅ ONLINE ($HTTP_CODE)"
    else
        STATUS_CLASS="status-down"
        STATUS_TEXT="❌ OFFLINE ($HTTP_CODE)"
    fi
    
    cat >> "$OUTPUT" << INNEREOF
                <div class="domain-card">
                    <h3>$DOMAIN</h3>
                    <p class='$STATUS_CLASS'>$STATUS_TEXT</p>
                </div>
INNEREOF
done

cat >> "$OUTPUT" << 'EOF'
            </div>
        </div>
        
        <p class="timestamp">Terakhir diperbarui: $(date "+%d %B %Y %H:%M:%S WIB")</p>
    </div>
</body>
</html>
EOF

echo "✅ Status page generated at $OUTPUT"