#!/bin/bash
# Send Telegram alert for Hermes service status changes
# Auto-generated by FASE 6 (2026-05-06)

BOT_TOKEN="8673939697:AAEFPs2G-xhbTl8eJ7hnPk5ezc4PZeLhSrU"
CHAT_ID="5807834405"
MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
    echo "Usage: $0 \"message\""
    exit 1
fi

# Escape special characters for JSON
ESCAPED_MSG=$(echo "$MESSAGE" | sed 's/"/\\"/g' | sed 's/\//\\\//g')

# Send to Telegram
RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
    -H "Content-Type: application/json" \
    -d "{\"chat_id\": \"$CHAT_ID\", \"text\": \"$ESCAPED_MSG\", \"parse_mode\": \"HTML\"}")

# Check response
if echo "$RESPONSE" | grep -q '"ok":true'; then
    echo "✅ Telegram alert sent"
else
    echo "❌ Failed to send Telegram alert: $RESPONSE"
    exit 1
fi